import type { NodeDefinition, WorkflowItem } from './types';

export const NODE_CATALOG: NodeDefinition[] = [
  // --- TRIGGERS ---
  {
    subType: 'webhook',
    category: 'trigger',
    name: 'Webhook Trigger',
    description: 'Trigger automation on incoming HTTP POST/GET request',
    icon: '⚡',
    color: '#3b82f6',
    defaultConfig: {
      path: '/api/workflow/webhook-1',
      method: 'POST',
      auth: 'none',
    },
  },
  {
    subType: 'schedule',
    category: 'trigger',
    name: 'Schedule (Cron)',
    description: 'Run automation at set intervals (e.g., hourly, daily)',
    icon: '⏱️',
    color: '#8b5cf6',
    defaultConfig: {
      cron: '0 9 * * 1-5',
      timezone: 'UTC',
    },
  },
  {
    subType: 'doc_created',
    category: 'trigger',
    name: 'On Doc Created',
    description: 'Triggers when a new page or doc is added to Nexio',
    icon: '📄',
    color: '#06b6d4',
    defaultConfig: {
      workspaceFilter: 'current',
      tagFilter: '',
    },
  },
  {
    subType: 'manual',
    category: 'trigger',
    name: 'Manual Trigger',
    description: 'Trigger workflow manually with custom test input',
    icon: '▶️',
    color: '#10b981',
    defaultConfig: {
      testInput: '{"query": "Summarize the latest AI research trends"}',
    },
  },

  // --- AI & LLM ---
  {
    subType: 'llm_chat',
    category: 'ai',
    name: 'LLM Generator',
    description: 'Prompt GPT-4o, Claude 3.5, or Nexio Copilot',
    icon: '🧠',
    color: '#ec4899',
    defaultConfig: {
      model: 'gpt-4o',
      temperature: 0.7,
      systemPrompt: 'You are an advanced AI automation assistant. Process the input and provide structured markdown output.',
      prompt: '{{$json.query || $json.body}}',
    },
  },
  {
    subType: 'ai_agent',
    category: 'ai',
    name: 'AI Agent (ReAct)',
    description: 'Multi-step autonomous agent with web search & tools',
    icon: '🤖',
    color: '#f43f5e',
    defaultConfig: {
      model: 'claude-3-5-sonnet',
      maxSteps: 5,
      goal: 'Analyze the topic, fetch context, and generate a comprehensive executive summary.',
    },
  },
  {
    subType: 'summarizer',
    category: 'ai',
    name: 'Doc Summarizer',
    description: 'Extract bullet points, key takeaways, and action items',
    icon: '✨',
    color: '#a855f7',
    defaultConfig: {
      format: 'bullet-points',
      maxLength: 500,
    },
  },
  {
    subType: 'fal_image',
    category: 'ai',
    name: 'Fal AI Image Generator',
    description: 'Generate stunning illustrations via Flux or SDXL',
    icon: '🎨',
    color: '#f97316',
    defaultConfig: {
      model: 'flux-schnell',
      prompt: 'Clean modern minimalist SaaS workflow illustration, high resolution',
      aspectRatio: '16:9',
    },
  },

  // --- LOGIC ---
  {
    subType: 'condition',
    category: 'logic',
    name: 'If / Else Condition',
    description: 'Branch your workflow based on rules and values',
    icon: '🔀',
    color: '#eab308',
    defaultConfig: {
      field: 'status',
      operator: 'equals',
      value: 'success',
    },
  },
  {
    subType: 'code',
    category: 'logic',
    name: 'Code (JavaScript)',
    description: 'Transform data using custom JavaScript functions',
    icon: '💻',
    color: '#14b8a6',
    defaultConfig: {
      code: '// Return transformed payload\nreturn {\n  ...items[0],\n  timestamp: Date.now(),\n  processed: true\n};',
    },
  },
  {
    subType: 'delay',
    category: 'logic',
    name: 'Delay (Wait)',
    description: 'Pause execution for a specified duration',
    icon: '⏳',
    color: '#64748b',
    defaultConfig: {
      durationSeconds: 5,
    },
  },

  // --- ACTIONS ---
  {
    subType: 'create_doc',
    category: 'action',
    name: 'Create Nexio Doc',
    description: 'Automatically create a new page or whiteboard in Nexio',
    icon: '📝',
    color: '#2563eb',
    defaultConfig: {
      docTitle: 'AI Generated Report - {{new Date().toLocaleDateString()}}',
      content: '{{$json.output || $json.summary}}',
      mode: 'page',
    },
  },
  {
    subType: 'http_request',
    category: 'action',
    name: 'HTTP Request (API)',
    description: 'Make REST API calls to external services',
    icon: '🌐',
    color: '#0284c7',
    defaultConfig: {
      method: 'POST',
      url: 'https://api.example.com/v1/data',
      headers: '{\n  "Content-Type": "application/json"\n}',
    },
  },
  {
    subType: 'send_email',
    category: 'action',
    name: 'Send Email',
    description: 'Deliver email notifications with HTML/Markdown content',
    icon: '📧',
    color: '#6366f1',
    defaultConfig: {
      to: 'team@nexio.internal',
      subject: 'Nexio Automation Alert: New AI Report',
    },
  },
  {
    subType: 'slack_message',
    category: 'action',
    name: 'Slack Notification',
    description: 'Send messages to Slack channels or users',
    icon: '💬',
    color: '#4a154b',
    defaultConfig: {
      channel: '#general',
      text: '🤖 *Nexio Automation:* Completed workflow execution successfully.',
    },
  },
];

export const STARTER_WORKFLOWS: WorkflowItem[] = [
  {
    id: 'wf-doc-ai-summarizer',
    name: 'AI Document Summarizer & Insights',
    description: 'Automatically analyzes new Nexio pages, extracts action items with Claude 3.5, and appends a summary note.',
    active: true,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 3600000 * 4,
    executionCount: 14,
    lastRunAt: Date.now() - 1800000,
    lastRunStatus: 'success',
    nodes: [
      {
        id: 'node-1',
        type: 'trigger',
        subType: 'doc_created',
        name: 'On Doc Created',
        description: 'Triggers when a new document is added',
        position: { x: 80, y: 180 },
        status: 'idle',
        config: { workspaceFilter: 'current', tagFilter: '' },
      },
      {
        id: 'node-2',
        type: 'ai',
        subType: 'llm_chat',
        name: 'Claude 3.5 Sonnet Analyzer',
        description: 'Summarizes key points and extracts action items',
        position: { x: 380, y: 180 },
        status: 'idle',
        config: {
          model: 'claude-3-5-sonnet',
          temperature: 0.5,
          systemPrompt: 'Summarize the document into 3 key takeaways and a bulleted list of next steps.',
          prompt: '{{$json.content}}',
        },
      },
      {
        id: 'node-3',
        type: 'action',
        subType: 'create_doc',
        name: 'Save Executive Summary',
        description: 'Creates a summary page in Nexio',
        position: { x: 700, y: 180 },
        status: 'idle',
        config: {
          docTitle: 'Summary: {{$json.title}}',
          content: '{{$json.output}}',
          mode: 'page',
        },
      },
    ],
    connections: [
      { id: 'c1', fromNodeId: 'node-1', fromPort: 'output', toNodeId: 'node-2', toPort: 'input' },
      { id: 'c2', fromNodeId: 'node-2', fromPort: 'output', toNodeId: 'node-3', toPort: 'input' },
    ],
  },
  {
    id: 'wf-web-research-agent',
    name: 'Autonomous Web Research & Knowledge Sync',
    description: 'Receives research topics via Webhook, searches the web with AI, fact-checks, and writes a detailed whitepaper.',
    active: true,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 3600000 * 12,
    executionCount: 29,
    lastRunAt: Date.now() - 7200000,
    lastRunStatus: 'success',
    nodes: [
      {
        id: 'w2-node-1',
        type: 'trigger',
        subType: 'webhook',
        name: 'Incoming Webhook',
        description: 'Receives research prompt via POST',
        position: { x: 80, y: 160 },
        status: 'idle',
        config: { path: '/api/workflow/research', method: 'POST', auth: 'bearer' },
      },
      {
        id: 'w2-node-2',
        type: 'ai',
        subType: 'ai_agent',
        name: 'Deep Research Agent',
        description: 'Conducts autonomous research & synthesis',
        position: { x: 380, y: 160 },
        status: 'idle',
        config: {
          model: 'gpt-4o',
          maxSteps: 6,
          goal: 'Perform structured deep dive on topic and provide citations.',
        },
      },
      {
        id: 'w2-node-3',
        type: 'action',
        subType: 'create_doc',
        name: 'Publish Research Doc',
        description: 'Generates formatted Nexio Doc',
        position: { x: 700, y: 160 },
        status: 'idle',
        config: {
          docTitle: 'Deep Dive: {{$json.topic || "Research Brief"}}',
          content: '{{$json.output}}',
          mode: 'page',
        },
      },
      {
        id: 'w2-node-4',
        type: 'action',
        subType: 'slack_message',
        name: 'Slack Notification',
        description: 'Alerts the team channel with the new doc link',
        position: { x: 700, y: 320 },
        status: 'idle',
        config: {
          channel: '#research',
          text: '🚀 *New AI Whitepaper Generated:* {{$json.docTitle}}',
        },
      },
    ],
    connections: [
      { id: 'cw2-1', fromNodeId: 'w2-node-1', fromPort: 'output', toNodeId: 'w2-node-2', toPort: 'input' },
      { id: 'cw2-2', fromNodeId: 'w2-node-2', fromPort: 'output', toNodeId: 'w2-node-3', toPort: 'input' },
      { id: 'cw2-3', fromNodeId: 'w2-node-2', fromPort: 'output', toNodeId: 'w2-node-4', toPort: 'input' },
    ],
  },
  {
    id: 'wf-support-classifier',
    name: 'Smart Customer Support Ticket Classifier',
    description: 'Classifies support queries, checks urgency, and routes critical bugs to Slack while sending an automated email response.',
    active: false,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 2,
    executionCount: 8,
    lastRunAt: Date.now() - 86400000 * 3,
    lastRunStatus: 'success',
    nodes: [
      {
        id: 'w3-node-1',
        type: 'trigger',
        subType: 'manual',
        name: 'Customer Request Trigger',
        description: 'Ingests new customer feedback',
        position: { x: 80, y: 200 },
        status: 'idle',
        config: { testInput: '{"email": "client@acme.com", "issue": "Unable to export markdown docs"}' },
      },
      {
        id: 'w3-node-2',
        type: 'ai',
        subType: 'llm_chat',
        name: 'Sentiment & Priority Classifier',
        description: 'Evaluates priority: High, Medium, or Low',
        position: { x: 380, y: 200 },
        status: 'idle',
        config: {
          model: 'gpt-4o',
          temperature: 0.2,
          systemPrompt: 'Classify priority as high/medium/low and summarize sentiment.',
          prompt: '{{$json.issue}}',
        },
      },
      {
        id: 'w3-node-3',
        type: 'logic',
        subType: 'condition',
        name: 'Check If High Priority',
        description: 'Branches based on priority level',
        position: { x: 680, y: 200 },
        status: 'idle',
        config: { field: 'priority', operator: 'equals', value: 'high' },
      },
      {
        id: 'w3-node-4',
        type: 'action',
        subType: 'slack_message',
        name: 'Urgent Slack Ping',
        description: 'Pings on-call engineering',
        position: { x: 960, y: 140 },
        status: 'idle',
        config: { channel: '#support-urgent', text: '🚨 *High Priority Issue:* {{$json.issue}}' },
      },
      {
        id: 'w3-node-5',
        type: 'action',
        subType: 'send_email',
        name: 'Send Acknowledgement',
        description: 'Auto-reply to user',
        position: { x: 960, y: 280 },
        status: 'idle',
        config: { to: '{{$json.email}}', subject: 'We received your report' },
      },
    ],
    connections: [
      { id: 'cw3-1', fromNodeId: 'w3-node-1', fromPort: 'output', toNodeId: 'w3-node-2', toPort: 'input' },
      { id: 'cw3-2', fromNodeId: 'w3-node-2', fromPort: 'output', toNodeId: 'w3-node-3', toPort: 'input' },
      { id: 'cw3-3', fromNodeId: 'w3-node-3', fromPort: 'output', toNodeId: 'w3-node-4', toPort: 'input' },
      { id: 'cw3-4', fromNodeId: 'w3-node-3', fromPort: 'output', toNodeId: 'w3-node-5', toPort: 'input' },
    ],
  },
];
